CREATE TABLE IF NOT EXISTS mrt_liveboard_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(32) NOT NULL,
  operator VARCHAR(32) NOT NULL,
  updated_at VARCHAR(64) NOT NULL,
  row_count INT NOT NULL,
  rows_json CLOB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mrt_liveboard_snapshot_operator_updated_at
ON mrt_liveboard_snapshot (operator, updated_at);
