CREATE TABLE IF NOT EXISTS mrt_liveboard_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(32) NOT NULL,
  operator VARCHAR(32) NOT NULL,
  updated_at VARCHAR(64) NOT NULL,
  row_count INT NOT NULL,
  rows_json CLOB NOT NULL
);

DELETE FROM mrt_liveboard_snapshot
WHERE id NOT IN (
  SELECT MAX(id)
  FROM mrt_liveboard_snapshot
  GROUP BY source, operator, updated_at
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_mrt_liveboard_snapshot_source_operator_updated_at
ON mrt_liveboard_snapshot (source, operator, updated_at);

CREATE INDEX IF NOT EXISTS idx_mrt_liveboard_snapshot_operator_updated_at
ON mrt_liveboard_snapshot (operator, updated_at);

CREATE TABLE IF NOT EXISTS mrt_liveboard_backfill_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(32) NOT NULL,
  operator VARCHAR(32) NOT NULL,
  consumer_name VARCHAR(64) NOT NULL,
  cursor_at VARCHAR(64) NOT NULL,
  updated_at VARCHAR(64) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_mrt_liveboard_backfill_state_source_operator_consumer
ON mrt_liveboard_backfill_state (source, operator, consumer_name);
